---
# Create temporary Directory
- name: Create temporary directory
  win_file:
    path: C:\temp
    state: directory

## requirements
- name: Download OpenJDK1.8
  win_get_url:
    url: http://libs-websoft9-com.oss-cn-qingdao.aliyuncs.com/apps/Windows/java-1.8.0-openjdk-1.8.0.222-1.b10.ojdkbuild.windows.x86_64.msi
    dest: C:\temp\openjdk-1.8.0.msi

- name: Install OpenJDK1.8
  win_package:
    path: C:\temp\openjdk-1.8.0.msi
    product_id: openjdk
    arguments:
        - /quiet
        - /norestart

# 下载
- name: Download SQLServer Install tool
  win_get_url:
    url: https://download.microsoft.com/download/5/E/9/5E9B18CC-8FD5-467E-B5BF-BADE39C51F73/SQLServer2017-SSEI-Expr.exe
    dest: C:\temp\SQLServer2017.exe

## 安装 SQLServer
- name: Copy ConfigurationFile.ini
  win_template:
    src: ConfigurationFile_2017.ini.j2
    dest: C:\temp\ConfigurationFile.ini

- name: Install SQLServer2017 ENU
  win_shell:
    .\SQLServer2017.exe /ACTION=Install /CONFIGURATIONFILE=ConfigurationFile.ini /Lang=en-US /Q /IACCEPTSQLSERVERLICENSETERMS=True
  args:
    chdir: C:\temp\
  when: language == "ENU"

- name: Install SQLServer2017 CHS
  win_shell:
    .\SQLServer2017.exe /ACTION=Install /CONFIGURATIONFILE=ConfigurationFile.ini /Lang=zh-CN /Q /IACCEPTSQLSERVERLICENSETERMS=True
  args:
    chdir: C:\temp\
  when: language == "CHS"

- name: Reboot Machine
  win_reboot:
    reboot_timeout: 3600

## 安装SSMS
- name: Download SSMS
  win_get_url:
    url: https://download.microsoft.com/download/2/9/C/29CC9731-CE3B-4EC8-89D8-E6B8EE88EAF5/SSMS-Setup-{{language}}.exe
    dest: C:\temp

- name: Install SSMS
  win_shell:
    .\SSMS-Setup-{{language}}.exe /install /quiet /norestart
  args:
    chdir: C:\temp

# 快捷方式
- name: Create SSMS lnk
  win_shortcut:
    src: C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\Ssms.exe
    dest: C:\Users\Public\Desktop\Microsoft SQL Server Management Studio 18.lnk
    icon: C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\ssms.ico

## 创建密码凭证文件
- name: Create Credentials Directory
  win_file:
    path: C:\Credentials\
    state: directory

- name: Copy password.txt to Credentials
  win_template:
    src: password.txt.j2
    dest: C:\Credentials\password.txt

- name: Create password.lnk on desktop
  win_shortcut:
    src: C:\Credentials\password.txt
    dest: C:\Users\Public\Desktop\password.lnk

## 删除临时目录
- name: Delete temporary directory
  win_file:
    path: C:\temp
    state: absent


